import 'dart:async';

import 'package:flutter/foundation.dart';

import 'package:html/dom.dart' as dom;
import 'package:html/parser.dart';

import 'package:lolisnatcher/src/boorus/doujin/doujin_listing_tag_backfill.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_recommendation_engine.dart';
import 'package:lolisnatcher/src/data/booru_item.dart';
import 'package:lolisnatcher/src/data/meta_tag.dart';
import 'package:lolisnatcher/src/data/tag.dart';
import 'package:lolisnatcher/src/data/tag_type.dart';
import 'package:lolisnatcher/src/handlers/booru_handler.dart';
import 'package:lolisnatcher/src/handlers/reader_handler.dart';
import 'package:lolisnatcher/src/utils/dio_network.dart';

/// asmhentai.com — server-rendered HTML, no API.
///
///   `/?page=N`                 the listing
///   `/search/?q=<q>&page=N`    search
///   `/g/{id}/`                 a gallery
///   `/login/`                  username + password, session in a cookie
///
/// Images live on a separate host under a two-part path whose first segment
/// is a shard that VARIES per gallery (`/018/676997/1.jpg`), so it is always
/// read off the page rather than assumed. Page N is `N.jpg`, its thumbnail
/// `Nt.jpg`, and the cover `thumb.jpg`.
///
/// The site publishes no related/recommended, so both are generated by
/// [DoujinRecommendationEngine].
class AsmHentaiHandler extends BooruHandler with DoujinListingTagBackfill {
  AsmHentaiHandler(super.booru, super.limit);

  static const String _site = 'https://asmhentai.com';

  @override
  bool get hasReader => true;

  @override
  bool get hasLoadItemSupport => true;

  @override
  bool get shouldUpdateIteminTagView => true;

  @override
  bool get hasNativeOrSupport => false;

  @override
  String translateOrSyntax(String tags) => BooruHandler.dropOrGroupsWithWarning(tags, className);

  @override
  List<String> get animatedPreviewFilters => const [];

  @override
  Map<String, String> getHeaders() => {
    ...super.getHeaders(),
    'Referer': '$_site/',
    if (_sessionCookie.isNotEmpty) 'Cookie': _sessionCookie,
  };

  @override
  String validateTags(String tags) => tags.trim();

  @override
  String makePostURL(String id) => '$_site/g/$id/';

  // ── login ─────────────────────────────────────────────────────────────

  String _sessionCookie = '';

  @override
  bool get hasSignInSupport => true;

  @override
  Future<bool> canSignIn() async =>
      (booru.userID?.isNotEmpty ?? false) && (booru.apiKey?.isNotEmpty ?? false);

  @override
  Future<bool> isSignedIn() async => _sessionCookie.isNotEmpty;

  /// Posts the site's own login form and keeps the session cookie it hands
  /// back. Used for gated content and account features; browsing works
  /// signed out.
  @override
  Future<bool> signIn() async {
    if (!await canSignIn()) return false;
    try {
      final response = await DioNetwork.post(
        '$_site/login/',
        headers: {
          ...super.getHeaders(),
          'Referer': '$_site/login/',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        data: {
          'username': booru.userID,
          'password': booru.apiKey,
          'remember_me': 'on',
          'go_login': '',
        },
      );
      final List<String> cookies = response.headers.map['set-cookie'] ?? const [];
      final String session = cookies.map((c) => c.split(';').first).join('; ');
      if (session.isEmpty) return false;
      _sessionCookie = session;
      return true;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<dynamic> signOut({bool fromError = false}) async {
    _sessionCookie = '';
    return true;
  }

  // ── the doujin query protocol ─────────────────────────────────────────

  static final RegExp _protocol = RegExp(r'^(id|related|recommend):(.+)$', caseSensitive: false);

  static ({String kind, String id})? _parseProtocol(String tags) {
    final match = _protocol.firstMatch(tags.trim());
    if (match == null) return null;
    return (kind: match.group(1)!.toLowerCase(), id: match.group(2)!.trim());
  }

  @override
  String makeURL(String tags) {
    final protocol = _parseProtocol(tags);
    final int page = pageNum < 1 ? 1 : pageNum;
    if (protocol != null) {
      if (protocol.kind == 'id') return '$_site/g/${protocol.id}/';
      // related/recommend do their own fetching; this is a cheap valid page.
      return '$_site/?page=1';
    }
    final String query = tags.trim();
    if (query.isEmpty) return '$_site/?page=$page';
    return '$_site/search/?q=${Uri.encodeQueryComponent(query)}&page=$page';
  }

  // ── parsing ───────────────────────────────────────────────────────────

  /// The shard segment of an image path (`//images.asmhentai.com/018/<id>/…`).
  /// It differs per gallery, so it is only ever read from the page.
  static final RegExp _imagePath = RegExp(r'images\.asmhentai\.com/([^/]+)/(\d+)/');

  static String _absolute(String url) => url.startsWith('//') ? 'https:$url' : url;

  @override
  FutureOr<List> parseListFromResponse(dynamic response) async {
    final protocol = _parseProtocol(currentTags);
    if (protocol != null && protocol.kind != 'id') {
      return protocol.kind == 'related'
          ? await _fetchRelated(protocol.id)
          : await _fetchRecommended(protocol.id);
    }

    final String body = response.data.toString();
    if (protocol != null && protocol.kind == 'id') {
      final item = _itemFromGalleryPage(protocol.id, body);
      return item == null ? [] : [item];
    }
    return _itemsFromListing(body);
  }

  /// [parseListFromResponse] already builds finished items, so the base class's
  /// per-entry hook is a passthrough. Without this override it would replace
  /// every one of them with the default blank [BooruItem] and the grid would
  /// fill with empty cards.
  @override
  FutureOr<BooruItem?> parseItemFromResponse(dynamic responseItem, int index) =>
      responseItem is BooruItem ? responseItem : null;


  /// Exposed so the listing parser can be exercised against real markup.
  @visibleForTesting
  List<BooruItem> itemsFromListingForTests(String body) => _itemsFromListing(body);

  /// Exposed for the same reason: tag namespaces come from link paths.
  @visibleForTesting
  List<Tag> tagsFromHtmlForTests(String body) => _tagsFrom(parse(body));

  @visibleForTesting
  static int pageCountForTests(String body) => _pageCount(parse(body), body);

  List<BooruItem> _itemsFromListing(String body) {
    final dom.Document doc = parse(body);
    final List<BooruItem> out = [];
    final Set<String> seen = {};

    for (final card in doc.querySelectorAll('div.image')) {
      final anchor = card.querySelector('a[href^="/g/"]');
      final img = card.querySelector('img');
      if (anchor == null || img == null) continue;

      final String href = anchor.attributes['href'] ?? '';
      final String id = RegExp(r'/g/(\d+)').firstMatch(href)?.group(1) ?? '';
      if (id.isEmpty || !seen.add(id)) continue;

      final String thumb = _absolute(
        img.attributes['data-src'] ?? img.attributes['src'] ?? '',
      );
      if (thumb.isEmpty || thumb.startsWith('data:')) continue;

      // The caption lives in the sibling block, not inside div.image.
      String title = img.attributes['alt'] ?? '';
      final parentNode = card.parent;
      final caption = parentNode?.querySelector('h2.caption') ?? parentNode?.querySelector('.caption');
      if (caption != null && caption.text.trim().isNotEmpty) title = caption.text.trim();

      final item = BooruItem(
        fileURL: thumb,
        sampleURL: thumb,
        thumbnailURL: thumb,
        tagsList: const [],
        postURL: '$_site/g/$id/',
        serverId: id,
      );
      item.description = title;
      out.add(item);
    }
    return out;
  }

  BooruItem? _itemFromGalleryPage(String id, String body) {
    final dom.Document doc = parse(body);
    final String title = doc.querySelector('h1')?.text.trim() ?? '';
    final match = _imagePath.firstMatch(body);
    final String shard = match?.group(1) ?? '';
    final String cover = shard.isEmpty
        ? ''
        : 'https://images.asmhentai.com/$shard/$id/thumb.jpg';

    final item = BooruItem(
      fileURL: cover,
      sampleURL: cover,
      thumbnailURL: cover,
      tagsList: _tagsFrom(doc),
      postURL: '$_site/g/$id/',
      serverId: id,
    );
    item.description = title;
    return item;
  }

  /// Tags come from their link paths, which carry the namespace:
  /// `/artist/x/`, `/tag/y/`, `/parody/z/`…
  static const Set<String> _namespaces = {
    'tag', 'artist', 'character', 'parody', 'group', 'language', 'category',
  };

  List<Tag> _tagsFrom(dom.Document doc) {
    final List<Tag> tags = [];
    final Set<String> seen = {};
    for (final a in doc.querySelectorAll('a[href]')) {
      final String href = a.attributes['href'] ?? '';
      final match = RegExp(r'^/([a-z]+)/([^/]+)/?$').firstMatch(href);
      if (match == null) continue;
      final String namespace = match.group(1)!;
      if (!_namespaces.contains(namespace)) continue;

      // The NAME comes from the href slug, not the link text: the text also
      // contains the site's gallery count in a nested span, which would
      // otherwise end up baked into every tag ("sleeping_(8,027)") and break
      // blacklists, stars and tag search.
      final String slug = match.group(2)!;
      final String name = slug.replaceAll('-', '_').toLowerCase();
      if (name.isEmpty) continue;

      final String full = namespace == 'tag' ? name : '$namespace:$name';
      if (!seen.add(full)) continue;

      final int count = _countFrom(a);
      tags.add(Tag(full, tagType: _typeOf(namespace), count: count));
    }
    return tags;
  }

  /// The gallery count the site prints beside a tag, e.g. "(8,027)".
  static int _countFrom(dom.Element anchor) {
    final String text = anchor.querySelector('.gallery_count')?.text ?? '';
    final digits = RegExp(r'[\d,]+').firstMatch(text)?.group(0)?.replaceAll(',', '');
    return int.tryParse(digits ?? '') ?? 0;
  }

  static TagType _typeOf(String namespace) => switch (namespace) {
    'artist' || 'group' => TagType.artist,
    'character' => TagType.character,
    'parody' => TagType.copyright,
    'language' || 'category' => TagType.meta,
    _ => TagType.none,
  };

  @override
  String? tagNamespace(String tag) {
    final int colon = tag.indexOf(':');
    if (colon == -1) return 'tag';
    final String namespace = tag.substring(0, colon);
    return _namespaces.contains(namespace) ? namespace : 'tag';
  }

  @override
  List<(String, String)> get tagNamespaceSections => const [
    ('artist', 'Artists'),
    ('group', 'Groups'),
    ('parody', 'Parodies'),
    ('character', 'Characters'),
    ('tag', 'Tags'),
    ('language', 'Languages'),
    ('category', 'Categories'),
  ];

  @override
  List<MetaTag> availableMetaTags() => [
    StringMetaTag(name: 'Artist', keyName: 'artist'),
    StringMetaTag(name: 'Group', keyName: 'group'),
    StringMetaTag(name: 'Series', keyName: 'parody'),
    StringMetaTag(name: 'Character', keyName: 'character'),
    StringMetaTag(name: 'Language', keyName: 'language'),
    StringMetaTag(name: 'Category', keyName: 'category'),
  ];

  /// Listing blocks carry a cover and a title but no tags, so card tags come
  /// from the gallery page.
  @override
  Future<List<Tag>> tagsForListingItem(BooruItem item) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return const [];
    final response = await DioNetwork.get('$_site/g/$id/', headers: getHeaders());
    if (response.statusCode != 200) return const [];
    return _tagsFrom(parse(response.data.toString()));
  }

  // ── detail + reader ───────────────────────────────────────────────────

  @override
  Future<({BooruItem? item, bool failed, String? error})> loadItem({
    required BooruItem item,
    dynamic cancelToken,
    bool withCapcthaCheck = false,
  }) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return (item: null, failed: true, error: 'no gallery id');

    try {
      final response = await DioNetwork.get('$_site/g/$id/', headers: getHeaders());
      if (response.statusCode != 200) {
        return (item: null, failed: true, error: 'status ${response.statusCode}');
      }
      final String body = response.data.toString();
      final dom.Document doc = parse(body);

      item.tagsList = _tagsFrom(doc);
      final String title = doc.querySelector('h1')?.text.trim() ?? '';
      if (title.isNotEmpty) item.description = title;

      final match = _imagePath.firstMatch(body);
      final String shard = match?.group(1) ?? '';
      if (shard.isEmpty) {
        return (item: null, failed: true, error: 'could not resolve the image host path');
      }

      final int pageCount = _pageCount(doc, body);
      if (pageCount <= 0) return (item: null, failed: true, error: 'gallery has no pages');

      final String base = 'https://images.asmhentai.com/$shard/$id';
      final List<BooruItem> pages = [
        for (int n = 1; n <= pageCount; n++)
          BooruItem(
            fileURL: '$base/$n.jpg',
            sampleURL: '$base/$n.jpg',
            thumbnailURL: '$base/${n}t.jpg',
            tagsList: const [],
            postURL: '$_site/g/$id/',
          ),
      ];

      ReaderHandler.instance.registerBook(item, pages);
      item.fileCountHint.value = pages.length;
      return (item: item, failed: false, error: null);
    } catch (e) {
      return (item: null, failed: true, error: e.toString());
    }
  }

  /// "Pages: 20" on the gallery page; the count of thumbnails is the fallback.
  static int _pageCount(dom.Document doc, String body) {
    final labelled = RegExp(r'Pages:\s*(\d+)', caseSensitive: false).firstMatch(body);
    final int fromLabel = int.tryParse(labelled?.group(1) ?? '') ?? 0;
    if (fromLabel > 0) return fromLabel;
    return doc.querySelectorAll('img[data-src*="t.jpg"]').length;
  }

  // ── generated Related / Recommended ───────────────────────────────────

  Future<BooruItem?> _sourceItem(String id) async {
    try {
      final response = await DioNetwork.get('$_site/g/$id/', headers: getHeaders());
      if (response.statusCode != 200) return null;
      return _itemFromGalleryPage(id, response.data.toString());
    } catch (_) {
      return null;
    }
  }

  Future<List<BooruItem>> _candidatesFor(BooruItem source) async {
    final List<String> queries = [
      for (final t in source.tagsList.take(4))
        t.fullString.split(':').last.replaceAll('_', ' '),
      DoujinRecommendationEngine.baseTitle(
        (source.description ?? '').split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => ''),
      ),
    ].where((q) => q.trim().length > 2).toList();

    final List<BooruItem> out = [];
    final Set<String> seen = {source.postURL};
    for (final query in queries) {
      try {
        final response = await DioNetwork.get(
          '$_site/search/?q=${Uri.encodeQueryComponent(query)}&page=1',
          headers: getHeaders(),
        );
        for (final item in _itemsFromListing(response.data.toString())) {
          if (seen.add(item.postURL)) out.add(item);
        }
      } catch (_) {
        // One dead query means fewer candidates, never a failed section.
      }
    }
    return out;
  }

  /// Candidates carry no tags (the listing doesn't publish them), so the
  /// strongest few are filled in from their gallery pages before ranking —
  /// otherwise Recommended would be title-similarity only.
  Future<void> _fillTags(List<BooruItem> items, {int limit = 12}) async {
    for (final item in items.take(limit)) {
      if (item.tagsList.isNotEmpty) continue;
      try {
        final response = await DioNetwork.get(item.postURL, headers: getHeaders());
        item.tagsList = _tagsFrom(parse(response.data.toString()));
      } catch (_) {}
    }
  }

  Future<List<BooruItem>> _fetchRelated(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    return DoujinRecommendationEngine.related(source, candidates);
  }

  Future<List<BooruItem>> _fetchRecommended(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    await _fillTags(candidates);
    String? artist;
    for (final t in source.tagsList) {
      if (t.fullString.startsWith('artist:')) {
        artist = t.fullString.substring('artist:'.length);
        break;
      }
    }
    return DoujinRecommendationEngine.rank(
      source,
      candidates,
      count: limit,
      sourceArtist: (artist?.isEmpty ?? true) ? null : artist,
    );
  }

  @override
  String? relatedVersionsQuery(BooruItem item) {
    final String id = item.serverId ?? '';
    return id.isEmpty ? null : 'related:$id';
  }
}
