import 'dart:async';

import 'package:flutter/foundation.dart';

import 'package:html/dom.dart' as dom;
import 'package:html/parser.dart';

import 'package:lolisnatcher/src/boorus/doujin/doujin_listing_tag_backfill.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_recommendation_engine.dart';
import 'package:lolisnatcher/src/data/booru_item.dart';
import 'package:lolisnatcher/src/data/meta_tag.dart';
import 'package:lolisnatcher/src/data/tag.dart';
import 'package:lolisnatcher/src/data/tag_type.dart';
import 'package:lolisnatcher/src/handlers/booru_handler.dart';
import 'package:lolisnatcher/src/handlers/reader_handler.dart';
import 'package:lolisnatcher/src/utils/dio_network.dart';

/// eahentai.com — a Next.js site.
///
///   `/?page=N`          the listing
///   `/search?q=<q>`     search
///   `/a/{id}`           a gallery
///   `/a/{id}/{n}`       one reader page - and its HTML lists EVERY page, so
///                       a single fetch yields the whole book
///   `/login`            the session
///
/// The visible markup carries almost no metadata: tags, authors and the
/// gallery's image hash live in the streamed hydration payload
/// (`self.__next_f.push([1,"…"])`), where tags and authors are pipe-separated
/// strings. That payload is decoded rather than scraped from the DOM.
///
/// Related and Recommended are generated by [DoujinRecommendationEngine].
class EaHentaiHandler extends BooruHandler with DoujinListingTagBackfill {
  EaHentaiHandler(super.booru, super.limit);

  static const String _site = 'https://eahentai.com';
  static const String _cdn = 'https://i.eahentai.com/file/ea-gallery';

  @override
  bool get hasReader => true;

  @override
  bool get hasLoadItemSupport => true;

  @override
  bool get shouldUpdateIteminTagView => true;

  @override
  bool get hasNativeOrSupport => false;

  @override
  String translateOrSyntax(String tags) => BooruHandler.dropOrGroupsWithWarning(tags, className);

  @override
  List<String> get animatedPreviewFilters => const [];

  @override
  Map<String, String> getHeaders() => {
    ...super.getHeaders(),
    'Referer': '$_site/',
    if (_sessionCookie.isNotEmpty) 'Cookie': _sessionCookie,
  };

  /// eahentai's CDN serves without a referer today; sending the one a browser
  /// would send keeps a future hotlink rule from silently blanking covers.
  @override
  Map<String, String> getMediaHeaders() => {'Referer': '$_site/'};

  @override
  String validateTags(String tags) => tags.trim();

  @override
  String makePostURL(String id) => '$_site/a/$id';

  // ── login ─────────────────────────────────────────────────────────────

  String _sessionCookie = '';

  @override
  bool get hasSignInSupport => true;

  @override
  Future<bool> canSignIn() async =>
      (booru.userID?.isNotEmpty ?? false) && (booru.apiKey?.isNotEmpty ?? false);

  @override
  Future<bool> isSignedIn() async => _sessionCookie.isNotEmpty;

  @override
  Future<bool> signIn() async {
    if (!await canSignIn()) return false;
    try {
      final response = await DioNetwork.post(
        '$_site/login',
        headers: {
          ...super.getHeaders(),
          'Referer': '$_site/login',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        data: {'username': booru.userID, 'email': booru.userID, 'password': booru.apiKey},
      );
      final List<String> cookies = response.headers.map['set-cookie'] ?? const [];
      final String session = cookies.map((c) => c.split(';').first).join('; ');
      if (session.isEmpty) return false;
      _sessionCookie = session;
      return true;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<dynamic> signOut({bool fromError = false}) async {
    _sessionCookie = '';
    return true;
  }

  // ── the doujin query protocol ─────────────────────────────────────────

  static final RegExp _protocol = RegExp(r'^(id|related|recommend):(.+)$', caseSensitive: false);

  static ({String kind, String id})? _parseProtocol(String tags) {
    final match = _protocol.firstMatch(tags.trim());
    if (match == null) return null;
    return (kind: match.group(1)!.toLowerCase(), id: match.group(2)!.trim());
  }

  @override
  String makeURL(String tags) {
    final protocol = _parseProtocol(tags);
    final int page = pageNum < 1 ? 1 : pageNum;
    if (protocol != null) {
      if (protocol.kind == 'id') return '$_site/a/${protocol.id}';
      return '$_site/?page=1';
    }
    final String query = tags.trim();
    if (query.isEmpty) return '$_site/?page=$page';
    return '$_site/search?q=${Uri.encodeQueryComponent(query)}&page=$page';
  }

  // ── the hydration payload ─────────────────────────────────────────────

  /// Joins and unescapes the streamed `self.__next_f.push([1,"…"])` chunks.
  /// Everything this site knows about a gallery lives in there.
  @visibleForTesting
  static String decodeNextPayload(String body) {
    final chunks = RegExp(r'self\.__next_f\.push\(\[1,"(.*?)"\]\)', dotAll: true)
        .allMatches(body)
        .map((m) => m.group(1) ?? '')
        .join();
    if (chunks.isEmpty) return '';
    return _unescape(chunks);
  }

  /// The chunks are JS string literals: \" \\ \n and \uXXXX.
  static String _unescape(String s) {
    final out = StringBuffer();
    for (int i = 0; i < s.length; i++) {
      if (s[i] != r'\' || i + 1 >= s.length) {
        out.write(s[i]);
        continue;
      }
      final String next = s[i + 1];
      switch (next) {
        case 'n':
          out.write('\n');
          i++;
        case 't':
          out.write('\t');
          i++;
        case 'r':
          out.write('\r');
          i++;
        case '"':
          out.write('"');
          i++;
        case r'\':
          out.write(r'\');
          i++;
        case '/':
          out.write('/');
          i++;
        case 'u':
          if (i + 5 < s.length) {
            final int? code = int.tryParse(s.substring(i + 2, i + 6), radix: 16);
            if (code != null) {
              out.writeCharCode(code);
              i += 5;
            } else {
              out.write(s[i]);
            }
          } else {
            out.write(s[i]);
          }
        default:
          out.write(s[i]);
      }
    }
    return out.toString();
  }

  /// Pipe-separated values of a payload field, e.g. `"tags":"a|b|c"`.
  @visibleForTesting
  static List<String> pipeField(String payload, String field) {
    final match = RegExp('"$field":"([^"]*)"').firstMatch(payload);
    final String raw = match?.group(1) ?? '';
    if (raw.trim().isEmpty) return const [];
    return [
      for (final part in raw.split('|'))
        if (part.trim().isNotEmpty) part.trim(),
    ];
  }

  /// The per-gallery hash the CDN paths are built from.
  @visibleForTesting
  static String galleryHash(String body) =>
      RegExp('galleries/([0-9a-f]{16,})/').firstMatch(body)?.group(1) ?? '';

  /// Tags and authors, namespaced the way the rest of the app expects.
  @visibleForTesting
  static List<Tag> tagsFromPayload(String payload) {
    final List<Tag> tags = [];
    final Set<String> seen = {};

    void add(String name, String? namespace, TagType type) {
      final String normalized = name.toLowerCase().replaceAll(' ', '_');
      if (normalized.isEmpty) return;
      final String full = namespace == null ? normalized : '$namespace:$normalized';
      if (!seen.add(full)) return;
      tags.add(Tag(full, tagType: type));
    }

    for (final a in pipeField(payload, 'author')) {
      add(a, 'artist', TagType.artist);
    }
    for (final t in pipeField(payload, 'tags')) {
      add(t, null, TagType.none);
    }
    for (final p in pipeField(payload, 'parody')) {
      add(p, 'parody', TagType.copyright);
    }
    for (final c in pipeField(payload, 'character')) {
      add(c, 'character', TagType.character);
    }
    return tags;
  }

  // ── parsing ───────────────────────────────────────────────────────────

  @override
  FutureOr<List> parseListFromResponse(dynamic response) async {
    final protocol = _parseProtocol(currentTags);
    if (protocol != null && protocol.kind != 'id') {
      return protocol.kind == 'related'
          ? await _fetchRelated(protocol.id)
          : await _fetchRecommended(protocol.id);
    }

    final String body = response.data.toString();
    if (protocol != null && protocol.kind == 'id') {
      final item = _itemFromGalleryPage(protocol.id, body);
      return item == null ? [] : [item];
    }
    return itemsFromListing(body);
  }

  /// [parseListFromResponse] already builds finished items, so the base class's
  /// per-entry hook is a passthrough. Without this override it would replace
  /// every one of them with the default blank [BooruItem] and the grid would
  /// fill with empty cards.
  @override
  FutureOr<BooruItem?> parseItemFromResponse(dynamic responseItem, int index) =>
      responseItem is BooruItem ? responseItem : null;


  /// Listing cards are `/a/{id}` links wrapping a cover image, with the title
  /// on the anchor's `aria-label` (the `<img alt>` is deliberately empty).
  ///
  /// The same id can appear more than once on a page: the hero card at the top
  /// also renders a "Read Now" button pointing at itself, and that anchor holds
  /// only an icon. Taking the first anchor per id therefore produced a card
  /// with no title and no cover, so the anchor that actually carries an image
  /// wins.
  @visibleForTesting
  List<BooruItem> itemsFromListing(String body) {
    final dom.Document doc = parse(body);
    final Map<String, BooruItem> byId = {};
    final List<String> order = [];

    for (final a in doc.querySelectorAll('a[href^="/a/"]')) {
      final String href = a.attributes['href'] ?? '';
      // Only gallery links, not the per-page reader routes (/a/{id}/{n}).
      final match = RegExp(r'^/a/(\d+)$').firstMatch(href);
      if (match == null) continue;
      final String id = match.group(1)!;

      final img = a.querySelector('img');
      final String thumb = (img?.attributes['src'] ?? img?.attributes['data-src'] ?? '').trim();
      final String title = (a.attributes['aria-label'] ??
              a.querySelector('p')?.text ??
              img?.attributes['alt'] ??
              '')
          .trim();

      final BooruItem? existing = byId[id];
      if (existing != null) {
        // Only ever upgrade: an anchor with a cover beats one without.
        if (thumb.isEmpty) continue;
        if (existing.thumbnailURL.isNotEmpty) continue;
      } else {
        order.add(id);
      }

      final item = BooruItem(
        fileURL: thumb,
        sampleURL: thumb,
        thumbnailURL: thumb,
        tagsList: const [],
        postURL: '$_site/a/$id',
        serverId: id,
      );
      item.description = title;
      byId[id] = item;
    }

    return [for (final id in order) byId[id]!];
  }

  BooruItem? _itemFromGalleryPage(String id, String body) {
    final dom.Document doc = parse(body);
    final String payload = decodeNextPayload(body);
    final String hash = galleryHash(body);
    final String cover = hash.isEmpty ? '' : '$_cdn/galleries/$hash/thumbnail/image1t.jpg';

    final item = BooruItem(
      fileURL: cover,
      sampleURL: cover,
      thumbnailURL: cover,
      tagsList: tagsFromPayload(payload),
      postURL: '$_site/a/$id',
      serverId: id,
    );
    item.description = doc.querySelector('h1')?.text.trim() ?? '';
    return item;
  }

  @override
  String? tagNamespace(String tag) {
    final int colon = tag.indexOf(':');
    if (colon == -1) return 'tag';
    return const {'artist', 'parody', 'character'}.contains(tag.substring(0, colon))
        ? tag.substring(0, colon)
        : 'tag';
  }

  @override
  List<(String, String)> get tagNamespaceSections => const [
    ('artist', 'Artists'),
    ('parody', 'Parodies'),
    ('character', 'Characters'),
    ('tag', 'Tags'),
  ];

  @override
  List<MetaTag> availableMetaTags() => [
    StringMetaTag(name: 'Artist', keyName: 'artist'),
    StringMetaTag(name: 'Series', keyName: 'parody'),
    StringMetaTag(name: 'Character', keyName: 'character'),
  ];

  /// Only the hero card on a listing page carries tags in the markup; the
  /// grid cards do not, so card tags come from each gallery's own page.
  @override
  Future<List<Tag>> tagsForListingItem(BooruItem item) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return const [];
    final response = await DioNetwork.get('$_site/a/$id', headers: getHeaders());
    if (response.statusCode != 200) return const [];
    return tagsFromPayload(decodeNextPayload(response.data.toString()));
  }

  // ── detail + reader ───────────────────────────────────────────────────

  @override
  Future<({BooruItem? item, bool failed, String? error})> loadItem({
    required BooruItem item,
    dynamic cancelToken,
    bool withCapcthaCheck = false,
  }) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return (item: null, failed: true, error: 'no gallery id');

    try {
      // The gallery page carries the metadata...
      final galleryResponse = await DioNetwork.get('$_site/a/$id', headers: getHeaders());
      if (galleryResponse.statusCode != 200) {
        return (item: null, failed: true, error: 'status ${galleryResponse.statusCode}');
      }
      final String galleryBody = galleryResponse.data.toString();
      final String payload = decodeNextPayload(galleryBody);
      item.tagsList = tagsFromPayload(payload);
      final String title = parse(galleryBody).querySelector('h1')?.text.trim() ?? '';
      if (title.isNotEmpty) item.description = title;

      // ...and any single reader page lists every image in the book.
      final readerResponse = await DioNetwork.get(
        '$_site/a/$id/0',
        headers: {...getHeaders(), 'Referer': '$_site/a/$id'},
      );
      final String readerBody = readerResponse.data.toString();
      final List<String> images = fullImageUrls(readerBody);
      if (images.isEmpty) {
        return (item: null, failed: true, error: 'could not resolve the page images');
      }

      final String hash = galleryHash(readerBody.isEmpty ? galleryBody : readerBody);
      final List<BooruItem> pages = [
        for (int i = 0; i < images.length; i++)
          BooruItem(
            fileURL: images[i],
            sampleURL: images[i],
            thumbnailURL: hash.isEmpty
                ? images[i]
                : '$_cdn/galleries/$hash/thumbnail/image${i + 1}t.jpg',
            tagsList: const [],
            postURL: '$_site/a/$id',
          ),
      ];

      ReaderHandler.instance.registerBook(item, pages);
      item.fileCountHint.value = pages.length;
      return (item: item, failed: false, error: null);
    } catch (e) {
      return (item: null, failed: true, error: e.toString());
    }
  }

  /// Every full-size page image on a reader page, in page order. The CDN
  /// serves them as `image<N>.webp`; the `thumbnail/` variants are excluded.
  @visibleForTesting
  static List<String> fullImageUrls(String body) {
    final matches = RegExp(r'https://i\.eahentai\.com/file/ea-gallery/galleries/[0-9a-f]+/image(\d+)\.(?:webp|jpg|png)')
        .allMatches(body);
    final Map<int, String> byIndex = {};
    for (final m in matches) {
      final int? n = int.tryParse(m.group(1) ?? '');
      if (n == null) continue;
      byIndex.putIfAbsent(n, () => m.group(0)!);
    }
    final keys = byIndex.keys.toList()..sort();
    return [for (final k in keys) byIndex[k]!];
  }

  // ── generated Related / Recommended ───────────────────────────────────

  Future<BooruItem?> _sourceItem(String id) async {
    try {
      final response = await DioNetwork.get('$_site/a/$id', headers: getHeaders());
      if (response.statusCode != 200) return null;
      return _itemFromGalleryPage(id, response.data.toString());
    } catch (_) {
      return null;
    }
  }

  Future<List<BooruItem>> _candidatesFor(BooruItem source) async {
    final List<String> queries = [
      for (final t in source.tagsList.take(4)) t.fullString.split(':').last.replaceAll('_', ' '),
      DoujinRecommendationEngine.baseTitle(
        (source.description ?? '').split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => ''),
      ),
    ].where((q) => q.trim().length > 2).toList();

    final List<BooruItem> out = [];
    final Set<String> seen = {source.postURL};
    for (final query in queries) {
      try {
        final response = await DioNetwork.get(
          '$_site/search?q=${Uri.encodeQueryComponent(query)}',
          headers: getHeaders(),
        );
        for (final item in itemsFromListing(response.data.toString())) {
          if (seen.add(item.postURL)) out.add(item);
        }
      } catch (_) {}
    }
    return out;
  }

  Future<List<BooruItem>> _fetchRelated(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    return DoujinRecommendationEngine.related(source, await _candidatesFor(source));
  }

  Future<List<BooruItem>> _fetchRecommended(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    String? artist;
    for (final t in source.tagsList) {
      if (t.fullString.startsWith('artist:')) {
        artist = t.fullString.substring('artist:'.length);
        break;
      }
    }
    return DoujinRecommendationEngine.rank(
      source,
      candidates,
      count: limit,
      sourceArtist: (artist?.isEmpty ?? true) ? null : artist,
    );
  }

  @override
  String? relatedVersionsQuery(BooruItem item) {
    final String id = item.serverId ?? '';
    return id.isEmpty ? null : 'related:$id';
  }
}
