import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';

import 'package:lolisnatcher/src/boorus/doujin/doujin_recommendation_engine.dart';
import 'package:lolisnatcher/src/data/booru_item.dart';
import 'package:lolisnatcher/src/data/meta_tag.dart';
import 'package:lolisnatcher/src/data/tag.dart';
import 'package:lolisnatcher/src/data/tag_type.dart';
import 'package:lolisnatcher/src/handlers/booru_handler.dart';
import 'package:lolisnatcher/src/handlers/reader_handler.dart';
import 'package:lolisnatcher/src/utils/dio_network.dart';

/// hentalk.pw — which runs **faccina**, an open-source gallery server with a
/// proper REST API, so none of the SvelteKit page markup needs parsing:
///
///   `GET /api/library?q=<query>&page=N`  search / browse
///   `GET /api/g/{id}`                    one gallery, with namespaced tags
///   `GET /image/{hash}/{page}`           a page image, 1-based
///
/// faccina has its own query syntax (`artist:"name"`, `-tag` to exclude,
/// `~` for OR), so the app's tag queries are TRANSLATED into it rather than
/// pasted in raw - see [translateQuery].
///
/// Related and Recommended are generated by [DoujinRecommendationEngine].
class FaccinaHandler extends BooruHandler {
  FaccinaHandler(super.booru, super.limit);

  /// The site this handler was configured for; faccina is self-hosted, so the
  /// host comes from the booru config rather than being hardcoded.
  String get _site {
    final String configured = booru.baseURL?.trim() ?? '';
    if (configured.isEmpty) return 'https://hentalk.pw';
    return configured.endsWith('/') ? configured.substring(0, configured.length - 1) : configured;
  }

  @override
  bool get hasReader => true;

  @override
  bool get hasLoadItemSupport => true;

  @override
  bool get shouldUpdateIteminTagView => true;

  @override
  bool get hasSizeData => false;

  @override
  bool get hasNativeOrSupport => false;

  @override
  String translateOrSyntax(String tags) => BooruHandler.dropOrGroupsWithWarning(tags, className);

  @override
  List<String> get animatedPreviewFilters => const [];

  @override
  Map<String, String> getHeaders() => {
    ...super.getHeaders(),
    'Referer': '$_site/',
    'Accept': 'application/json',
    if (_sessionCookie.isNotEmpty) 'Cookie': _sessionCookie,
  };

  static dynamic _json(dynamic data) => data is String ? jsonDecode(data) : data;

  @override
  String validateTags(String tags) => tags.trim();

  @override
  String makePostURL(String id) => '$_site/g/$id';

  // ── login ─────────────────────────────────────────────────────────────

  String _sessionCookie = '';

  @override
  bool get hasSignInSupport => true;

  @override
  Future<bool> canSignIn() async =>
      (booru.userID?.isNotEmpty ?? false) && (booru.apiKey?.isNotEmpty ?? false);

  @override
  Future<bool> isSignedIn() async => _sessionCookie.isNotEmpty;

  /// faccina exposes user accounts when the instance enables them (this one
  /// reports enableUsers). Login is a form post; the session rides in a
  /// cookie afterwards.
  @override
  Future<bool> signIn() async {
    if (!await canSignIn()) return false;
    try {
      final response = await DioNetwork.post(
        '$_site/login',
        headers: {
          ...super.getHeaders(),
          'Referer': '$_site/login',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        data: {'username': booru.userID, 'password': booru.apiKey},
      );
      final List<String> cookies = response.headers.map['set-cookie'] ?? const [];
      final String session = cookies.map((c) => c.split(';').first).join('; ');
      if (session.isEmpty) return false;
      _sessionCookie = session;
      return true;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<dynamic> signOut({bool fromError = false}) async {
    _sessionCookie = '';
    return true;
  }

  // ── query translation ─────────────────────────────────────────────────

  /// Turns the app's tag syntax into faccina's.
  ///
  /// The app writes tags as `namespace:some_tag` with underscores and a
  /// leading `-` to exclude. faccina wants the value quoted when it contains
  /// spaces (`artist:"asami asami"`) and reads underscores literally, so they
  /// are turned back into spaces. Anything already quoted is left alone.
  @visibleForTesting
  static String translateQuery(String tags) {
    final String trimmed = tags.trim();
    if (trimmed.isEmpty) return '';

    final List<String> out = [];
    // Split on whitespace, but keep quoted runs together.
    final matches = RegExp(r'"[^"]*"|\S+').allMatches(trimmed);
    for (final m in matches) {
      final String token = m.group(0)!;
      if (token.startsWith('"') || token.contains('"')) {
        out.add(token);
        continue;
      }

      String prefix = '';
      String rest = token;
      if (rest.startsWith('-') || rest.startsWith('~')) {
        prefix = rest.substring(0, 1);
        rest = rest.substring(1);
      }
      if (rest.isEmpty) continue;

      final int colon = rest.indexOf(':');
      if (colon > 0) {
        final String namespace = rest.substring(0, colon);
        final String value = rest.substring(colon + 1).replaceAll('_', ' ');
        out.add(value.contains(' ') ? '$prefix$namespace:"$value"' : '$prefix$namespace:$value');
      } else {
        final String value = rest.replaceAll('_', ' ');
        out.add(value.contains(' ') ? '$prefix"$value"' : '$prefix$value');
      }
    }
    return out.join(' ');
  }

  // ── the doujin query protocol ─────────────────────────────────────────

  static final RegExp _protocol = RegExp(r'^(id|related|recommend):(.+)$', caseSensitive: false);

  static ({String kind, String id})? _parseProtocol(String tags) {
    final match = _protocol.firstMatch(tags.trim());
    if (match == null) return null;
    return (kind: match.group(1)!.toLowerCase(), id: match.group(2)!.trim());
  }

  @override
  String makeURL(String tags) {
    final protocol = _parseProtocol(tags);
    final int page = pageNum < 1 ? 1 : pageNum;
    if (protocol != null) {
      if (protocol.kind == 'id') return '$_site/api/g/${protocol.id}';
      return '$_site/api/library?page=1';
    }
    final String query = translateQuery(tags);
    // NB: the parameter is `q`. `search=` is accepted and silently ignored,
    // which would return the whole unfiltered library.
    if (query.isEmpty) return '$_site/api/library?page=$page';
    return '$_site/api/library?q=${Uri.encodeQueryComponent(query)}&page=$page';
  }

  // ── parsing ───────────────────────────────────────────────────────────

  /// One archive row from either endpoint - they share a shape.
  @visibleForTesting
  BooruItem? itemFromArchive(dynamic row) {
    if (row is! Map) return null;
    final String id = row['id']?.toString() ?? '';
    final String hash = row['hash']?.toString() ?? '';
    if (id.isEmpty || hash.isEmpty) return null;

    // `thumbnail` is the PAGE NUMBER used as the cover, not a URL.
    final int coverPage = (row['thumbnail'] as num?)?.toInt() ?? 1;
    final String cover = '$_site/image/$hash/$coverPage';

    final item = BooruItem(
      fileURL: cover,
      sampleURL: cover,
      thumbnailURL: cover,
      tagsList: tagsFromArchive(row),
      postURL: '$_site/g/$id',
      serverId: id,
    );
    item.description = row['title']?.toString() ?? '';
    final int pages = (row['pages'] as num?)?.toInt() ?? 0;
    if (pages > 0) item.fileCountHint.value = pages;
    _hashes[id] = hash;
    return item;
  }

  /// id -> content hash, which every image URL needs.
  final Map<String, String> _hashes = {};

  /// faccina publishes tags already namespaced: `{namespace, name}`.
  @visibleForTesting
  static List<Tag> tagsFromArchive(Map row) {
    final List<Tag> tags = [];
    final Set<String> seen = {};
    for (final t in row['tags'] as List? ?? []) {
      if (t is! Map) continue;
      final String name = (t['name']?.toString() ?? '').trim().replaceAll(' ', '_').toLowerCase();
      if (name.isEmpty) continue;
      final String namespace = (t['namespace']?.toString() ?? '').trim().toLowerCase();
      final String full = (namespace.isEmpty || namespace == 'tag') ? name : '$namespace:$name';
      if (!seen.add(full)) continue;
      tags.add(Tag(full, tagType: _typeOf(namespace)));
    }
    return tags;
  }

  static TagType _typeOf(String namespace) => switch (namespace) {
    'artist' || 'circle' => TagType.artist,
    'character' => TagType.character,
    'parody' || 'series' => TagType.copyright,
    'magazine' || 'publisher' || 'language' => TagType.meta,
    _ => TagType.none,
  };

  @override
  String? tagNamespace(String tag) {
    final int colon = tag.indexOf(':');
    return colon == -1 ? 'tag' : tag.substring(0, colon);
  }

  @override
  List<(String, String)> get tagNamespaceSections => const [
    ('artist', 'Artists'),
    ('circle', 'Circles'),
    ('parody', 'Parodies'),
    ('character', 'Characters'),
    ('tag', 'Tags'),
    ('magazine', 'Magazines'),
    ('publisher', 'Publishers'),
  ];

  @override
  List<MetaTag> availableMetaTags() => [
    StringMetaTag(name: 'Artist', keyName: 'artist'),
    StringMetaTag(name: 'Circle', keyName: 'circle'),
    StringMetaTag(name: 'Series', keyName: 'parody'),
    StringMetaTag(name: 'Character', keyName: 'character'),
    StringMetaTag(name: 'Magazine', keyName: 'magazine'),
    StringMetaTag(name: 'Publisher', keyName: 'publisher'),
  ];

  @override
  FutureOr<List> parseListFromResponse(dynamic response) async {
    final protocol = _parseProtocol(currentTags);
    if (protocol != null && protocol.kind != 'id') {
      return protocol.kind == 'related'
          ? await _fetchRelated(protocol.id)
          : await _fetchRecommended(protocol.id);
    }

    final data = _json(response.data);
    if (data is! Map) return [];

    // /api/g/{id} returns a bare archive; /api/library returns a page of them.
    if (protocol != null && protocol.kind == 'id') {
      final item = itemFromArchive(data);
      return item == null ? [] : [item];
    }
    return [
      for (final row in data['archives'] as List? ?? [])
        if (itemFromArchive(row) != null) itemFromArchive(row)!,
    ];
  }

  /// [parseListFromResponse] already builds finished items, so the base class's
  /// per-entry hook is a passthrough. Without this override it would replace
  /// every one of them with the default blank [BooruItem] and the grid would
  /// fill with empty cards.
  @override
  FutureOr<BooruItem?> parseItemFromResponse(dynamic responseItem, int index) =>
      responseItem is BooruItem ? responseItem : null;


  // ── detail + reader ───────────────────────────────────────────────────

  Future<Map?> _archive(String id) async {
    try {
      final response = await DioNetwork.get('$_site/api/g/$id', headers: getHeaders());
      if (response.statusCode != 200) return null;
      final data = _json(response.data);
      return data is Map ? data : null;
    } catch (_) {
      return null;
    }
  }

  @override
  Future<({BooruItem? item, bool failed, String? error})> loadItem({
    required BooruItem item,
    dynamic cancelToken,
    bool withCapcthaCheck = false,
  }) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return (item: null, failed: true, error: 'no gallery id');

    final archive = await _archive(id);
    if (archive == null) return (item: null, failed: true, error: 'failed to load gallery');

    final String hash = archive['hash']?.toString() ?? _hashes[id] ?? '';
    if (hash.isEmpty) {
      return (item: null, failed: true, error: 'gallery has no content hash');
    }

    item.tagsList = tagsFromArchive(archive);
    final String title = archive['title']?.toString() ?? '';
    if (title.isNotEmpty) item.description = title;

    final int pageCount = (archive['pages'] as num?)?.toInt() ?? 0;
    if (pageCount <= 0) return (item: null, failed: true, error: 'gallery has no pages');

    // Page images are 1-based and served straight off the site.
    final List<BooruItem> pages = [
      for (int n = 1; n <= pageCount; n++)
        BooruItem(
          fileURL: '$_site/image/$hash/$n',
          sampleURL: '$_site/image/$hash/$n',
          thumbnailURL: '$_site/image/$hash/$n',
          tagsList: const [],
          postURL: '$_site/g/$id',
        ),
    ];

    ReaderHandler.instance.registerBook(item, pages);
    item.fileCountHint.value = pages.length;
    return (item: item, failed: false, error: null);
  }

  // ── generated Related / Recommended ───────────────────────────────────

  Future<BooruItem?> _sourceItem(String id) async {
    final archive = await _archive(id);
    return archive == null ? null : itemFromArchive(archive);
  }

  Future<List<BooruItem>> _candidatesFor(BooruItem source) async {
    // faccina's own syntax is used here too, so an artist candidate query is
    // an exact namespaced match rather than a loose word search.
    final List<String> queries = [
      for (final t in source.tagsList.take(4)) translateQuery(t.fullString),
      DoujinRecommendationEngine.baseTitle(
        (source.description ?? '').split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => ''),
      ),
    ].where((q) => q.trim().length > 2).toList();

    final List<BooruItem> out = [];
    final Set<String> seen = {source.postURL};
    for (final query in queries) {
      try {
        final response = await DioNetwork.get(
          '$_site/api/library?q=${Uri.encodeQueryComponent(query)}&page=1',
          headers: getHeaders(),
        );
        final data = _json(response.data);
        if (data is! Map) continue;
        for (final row in data['archives'] as List? ?? []) {
          final item = itemFromArchive(row);
          if (item != null && seen.add(item.postURL)) out.add(item);
        }
      } catch (_) {}
    }
    return out;
  }

  Future<List<BooruItem>> _fetchRelated(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    return DoujinRecommendationEngine.related(source, await _candidatesFor(source));
  }

  Future<List<BooruItem>> _fetchRecommended(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    String? artist;
    for (final t in source.tagsList) {
      if (t.fullString.startsWith('artist:')) {
        artist = t.fullString.substring('artist:'.length);
        break;
      }
    }
    return DoujinRecommendationEngine.rank(
      source,
      await _candidatesFor(source),
      count: limit,
      sourceArtist: (artist?.isEmpty ?? true) ? null : artist,
    );
  }

  @override
  String? relatedVersionsQuery(BooruItem item) {
    final String id = item.serverId ?? '';
    return id.isEmpty ? null : 'related:$id';
  }
}
