import 'dart:async';

import 'package:flutter/foundation.dart';

import 'package:html/dom.dart' as dom;
import 'package:html/parser.dart';

import 'package:lolisnatcher/src/boorus/doujin/doujin_listing_tag_backfill.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_recommendation_engine.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_tag_namespaces.dart';
import 'package:lolisnatcher/src/data/booru_item.dart';
import 'package:lolisnatcher/src/data/meta_tag.dart';
import 'package:lolisnatcher/src/data/tag.dart';
import 'package:lolisnatcher/src/data/tag_type.dart';
import 'package:lolisnatcher/src/handlers/booru_handler.dart';
import 'package:lolisnatcher/src/handlers/reader_handler.dart';
import 'package:lolisnatcher/src/utils/dio_network.dart';

/// hentaipaw.com — a Next.js app-router site; everything is server-rendered
/// into the page documents, there is no JSON API (capture 2026-09-02: 146
/// page-side calls, all scripts, analytics and ads).
///
///   `/?page=N`                              the listing (newest)
///   `/articles/search?keyword=<q>&page=N`   search
///   `/tags/{id}?page=N` and the same for artists/groups/parodies/characters
///   `/articles/{id}`                        a gallery
///   `/viewer?articleId={id}&page=N`         the reader; ONE viewer document
///                                           carries every page as
///                                           `{"src":"…/{id}/{sha1}/{n}.webp"}`
///
/// Images: `https://cdn.imagedeliveries.com/{id}/{sha1}/{n}.webp`, page
/// thumbnails `/{id}/thumbnails/{n}.webp`, cover `/{id}/thumbnails/cover.webp`.
/// Verified with curl: the CDN serves with or without a referer.
///
/// Listing cards carry a cover, a title and a language flag but no tags, so
/// card tags come from the gallery page. No related/recommended is
/// published; both are generated by [DoujinRecommendationEngine].
class HentaiPawHandler extends BooruHandler with DoujinListingTagBackfill, DoujinNamespacedTags {
  HentaiPawHandler(super.booru, super.limit);

  static const String _site = 'https://hentaipaw.com';
  static const String cdn = 'https://cdn.imagedeliveries.com';

  // No accounts are used: nothing reads a user id or key.
  @override
  bool get usesUserId => false;
  @override
  bool get usesApiKey => false;

  @override
  bool get hasReader => true;

  @override
  bool get hasLoadItemSupport => true;

  @override
  bool get shouldUpdateIteminTagView => true;

  @override
  bool get hasNativeOrSupport => false;

  @override
  String translateOrSyntax(String tags) => BooruHandler.dropOrGroupsWithWarning(tags, className);

  @override
  List<String> get animatedPreviewFilters => const [];

  /// The site sits behind Cloudflare and refuses non-browser clients (a
  /// datacenter curl is "Sorry, you have been blocked"); the page is asked for
  /// the way a browser would.
  @override
  Map<String, String> getHeaders() => {
    ...super.getHeaders(),
    'Referer': '$_site/',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9',
  };

  @override
  Map<String, String> getMediaHeaders() => {'Referer': '$_site/'};

  // The gallery page is fetched per card and the host is Cloudflare-fronted:
  // two at a time, spaced, so a grid of thirty does not look like a burst.
  @override
  int get tagBackfillConcurrency => 2;

  @override
  Duration get tagBackfillDelay => const Duration(milliseconds: 250);

  @override
  String validateTags(String tags) => tags.trim();

  @override
  String makePostURL(String id) => '$_site/articles/$id';

  // ── the doujin query protocol ─────────────────────────────────────────

  static final RegExp _protocol = RegExp(r'^(id|related|recommend):(.+)$', caseSensitive: false);

  static ({String kind, String id})? _parseProtocol(String tags) {
    final match = _protocol.firstMatch(tags.trim());
    if (match == null) return null;
    return (kind: match.group(1)!.toLowerCase(), id: match.group(2)!.trim());
  }

  /// Namespaced chips (`artist:neromashin`) search by keyword: the site's
  /// own tag pages are keyed by numeric id, which a bare name cannot reach.
  @visibleForTesting
  static String keywordFor(String query) {
    final String q = query.trim();
    final int colon = q.indexOf(':');
    if (colon > 0 && _namespaces.contains(q.substring(0, colon).toLowerCase())) {
      return q.substring(colon + 1).replaceAll('_', ' ').trim();
    }
    return q.replaceAll('_', ' ');
  }

  @override
  String makeURL(String tags) {
    final protocol = _parseProtocol(tags);
    final int page = pageNum < 1 ? 1 : pageNum;
    if (protocol != null) {
      if (protocol.kind == 'id') return makePostURL(protocol.id);
      return '$_site/?page=1';
    }
    final String query = keywordFor(tags);
    if (query.isEmpty) return '$_site/?page=$page';
    return '$_site/articles/search?keyword=${Uri.encodeQueryComponent(query)}&page=$page';
  }

  // ── parsing ───────────────────────────────────────────────────────────

  @override
  FutureOr<List> parseListFromResponse(dynamic response) async {
    final protocol = _parseProtocol(currentTags);
    if (protocol != null && protocol.kind != 'id') {
      return protocol.kind == 'related'
          ? await _fetchRelated(protocol.id)
          : await _fetchRecommended(protocol.id);
    }
    final String body = response.data.toString();
    if (protocol != null && protocol.kind == 'id') {
      final item = _itemFromArticlePage(protocol.id, body);
      return item == null ? [] : [item];
    }
    return _itemsFromListing(body);
  }

  @override
  FutureOr<BooruItem?> parseItemFromResponse(dynamic responseItem, int index) =>
      responseItem is BooruItem ? responseItem : null;

  @visibleForTesting
  List<BooruItem> itemsFromListingForTests(String body) => _itemsFromListing(body);

  @visibleForTesting
  BooruItem? itemFromArticleForTests(String id, String body) => _itemFromArticlePage(id, body);

  @visibleForTesting
  static List<String> pageUrlsForTests(String id, String viewerBody) => pageUrlsFrom(id, viewerBody);

  /// The flag on a card → the language the site means by it.
  static const Map<String, String> flagLanguages = {
    'us': 'english',
    'gb': 'english',
    'jp': 'japanese',
    'kr': 'korean',
    'cn': 'chinese',
    'tw': 'chinese',
    'es': 'spanish',
    'vi': 'vietnamese',
    'pt': 'portuguese',
    'br': 'portuguese',
    'th': 'thai',
    'fr': 'french',
    'de': 'german',
    'ru': 'russian',
    'it': 'italian',
    'id': 'indonesian',
  };

  static String coverUrl(String id) => '$cdn/$id/thumbnails/cover.webp';

  List<BooruItem> _itemsFromListing(String body) {
    final dom.Document doc = parse(body);
    final List<BooruItem> out = [];
    final Set<String> seen = {};

    for (final anchor in doc.querySelectorAll('a[href^="/articles/"]')) {
      final String href = anchor.attributes['href'] ?? '';
      final String id = RegExp(r'^/articles/(\d+)$').firstMatch(href)?.group(1) ?? '';
      if (id.isEmpty || !seen.add(id)) continue;
      final img = anchor.querySelector('img');
      if (img == null) continue;

      final String cover = img.attributes['src'] ?? coverUrl(id);
      // The caption block carries the clean title; the img alt appends the
      // language ("Title, English").
      final caption = anchor.querySelector('[title]');
      String title = caption?.attributes['title']?.trim() ?? '';
      if (title.isEmpty) {
        final String alt = img.attributes['alt'] ?? '';
        final int comma = alt.lastIndexOf(', ');
        title = comma > 0 ? alt.substring(0, comma) : alt;
      }

      final List<Tag> tags = [];
      final flag = anchor.querySelector('span.fi');
      final String code = RegExp(r'fi-([a-z]{2})').firstMatch(flag?.className ?? '')?.group(1) ?? '';
      final String? language = flagLanguages[code];
      if (language != null) tags.add(namespacedTag(language, 'language'));

      final item = BooruItem(
        fileURL: cover,
        sampleURL: cover,
        thumbnailURL: cover,
        tagsList: tags,
        postURL: makePostURL(id),
        serverId: id,
      );
      item.description = title;
      out.add(item);
    }
    return out;
  }

  BooruItem? _itemFromArticlePage(String id, String body) {
    final dom.Document doc = parse(body);
    final String title = doc.querySelector('h1')?.text.trim() ?? '';
    final String cover = coverUrl(id);
    final item = BooruItem(
      fileURL: cover,
      sampleURL: cover,
      thumbnailURL: cover,
      tagsList: _tagsFrom(doc),
      postURL: makePostURL(id),
      serverId: id,
    );
    item.description = title;
    item.fileCountHint.value = pageCountFrom(id, doc);
    return item;
  }

  /// Link path segment → namespace. The site files each kind under its own
  /// plural path (`/artists/19053`, `/tags/30`, `/languages/4`…).
  static const Map<String, String> _pathNamespaces = {
    'artists': 'artist',
    'groups': 'group',
    'parodies': 'parody',
    'characters': 'character',
    'tags': 'tag',
    'languages': 'language',
    'categories': 'category',
  };

  static const Set<String> _namespaces = {'artist', 'group', 'parody', 'character', 'tag', 'language', 'category'};

  List<Tag> _tagsFrom(dom.Document doc) {
    final dom.Element? block = doc.querySelector('#article-tag-information') ?? doc.body;
    if (block == null) return const [];
    final List<Tag> tags = [];
    final Set<String> seen = {};
    for (final a in block.querySelectorAll('a[href]')) {
      final match = RegExp('^/([a-z]+)/([0-9]+)\$').firstMatch(a.attributes['href'] ?? '');
      if (match == null) continue;
      final String? namespace = _pathNamespaces[match.group(1)!];
      if (namespace == null) continue;
      final String name = a.text.trim();
      if (name.isEmpty || name == 'N/A') continue;
      final Tag tag = namespacedTag(name, namespace);
      if (!seen.add(tag.fullString)) continue;
      tags.add(tag);
    }
    return tags;
  }

  /// Distinct `/viewer?articleId={id}&page=N` links on the gallery page.
  @visibleForTesting
  static int pageCountFrom(String id, dom.Document doc) {
    final Set<int> pages = {};
    for (final a in doc.querySelectorAll('a[href*="/viewer?articleId=$id"]')) {
      final m = RegExp(r'[?&]page=(\d+)').firstMatch(a.attributes['href'] ?? '');
      if (m != null) pages.add(int.parse(m.group(1)!));
    }
    return pages.length;
  }

  /// Every page image in a viewer document, in page order. The document
  /// embeds them as escaped JSON (`{\"src\":\"…/{id}/{sha1}/{n}.webp\"}`),
  /// so they are read by pattern rather than by parsing the RSC payload.
  static List<String> pageUrlsFrom(String id, String viewerBody) {
    final RegExp pattern = RegExp(
      'https://cdn\\.imagedeliveries\\.com/$id/[a-f0-9]+/(\\d+)\\.(webp|jpg|jpeg|png|avif)',
    );
    final Map<int, String> byPage = {};
    for (final m in pattern.allMatches(viewerBody)) {
      byPage.putIfAbsent(int.parse(m.group(1)!), () => m.group(0)!);
    }
    final List<int> order = byPage.keys.toList()..sort();
    return [for (final n in order) byPage[n]!];
  }

  @override
  List<(String, String)> get tagNamespaceSections => const [
    ('artist', 'Artists'),
    ('group', 'Groups'),
    ('parody', 'Parodies'),
    ('character', 'Characters'),
    ('tag', 'Tags'),
    ('language', 'Languages'),
    ('category', 'Categories'),
  ];

  @override
  List<MetaTag> availableMetaTags() => [
    StringMetaTag(name: 'Artist', keyName: 'artist'),
    StringMetaTag(name: 'Group', keyName: 'group'),
    StringMetaTag(name: 'Series', keyName: 'parody'),
    StringMetaTag(name: 'Character', keyName: 'character'),
    StringMetaTag(name: 'Language', keyName: 'language'),
    StringMetaTag(name: 'Category', keyName: 'category'),
  ];

  @override
  Future<List<Tag>> tagsForListingItem(BooruItem item) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return const [];
    final response = await DioNetwork.get(makePostURL(id), headers: getHeaders());
    if (response.statusCode != 200) return const [];
    return _tagsFrom(parse(response.data.toString()));
  }

  // ── detail + reader ───────────────────────────────────────────────────

  @override
  Future<({BooruItem? item, bool failed, String? error})> loadItem({
    required BooruItem item,
    dynamic cancelToken,
    bool withCapcthaCheck = false,
  }) async {
    final String id = item.serverId ?? '';
    if (id.isEmpty) return (item: null, failed: true, error: 'no gallery id');
    try {
      final article = await DioNetwork.get(makePostURL(id), headers: getHeaders());
      if (article.statusCode != 200) {
        return (item: null, failed: true, error: 'status ${article.statusCode} on the gallery page');
      }
      final dom.Document doc = parse(article.data.toString());
      final List<Tag> tags = _tagsFrom(doc);
      if (tags.isNotEmpty) item.tagsList = tags;
      final String title = doc.querySelector('h1')?.text.trim() ?? '';
      if (title.isNotEmpty) item.description = title;

      final viewer = await DioNetwork.get('$_site/viewer?articleId=$id&page=1', headers: getHeaders());
      if (viewer.statusCode != 200) {
        return (item: null, failed: true, error: 'status ${viewer.statusCode} on the viewer');
      }
      final List<String> urls = pageUrlsFrom(id, viewer.data.toString());
      if (urls.isEmpty) return (item: null, failed: true, error: 'the viewer lists no pages');

      final List<BooruItem> pages = [
        for (int i = 0; i < urls.length; i++)
          BooruItem(
            fileURL: urls[i],
            sampleURL: urls[i],
            thumbnailURL: '$cdn/$id/thumbnails/${i + 1}.webp',
            tagsList: const [],
            postURL: makePostURL(id),
          ),
      ];
      ReaderHandler.instance.registerBook(item, pages);
      item.fileCountHint.value = pages.length;
      return (item: item, failed: false, error: null);
    } catch (e) {
      return (item: null, failed: true, error: e.toString());
    }
  }

  // ── generated Related / Recommended ───────────────────────────────────

  Future<BooruItem?> _sourceItem(String id) async {
    try {
      final response = await DioNetwork.get(makePostURL(id), headers: getHeaders());
      if (response.statusCode != 200) return null;
      return _itemFromArticlePage(id, response.data.toString());
    } catch (_) {
      return null;
    }
  }

  Future<List<BooruItem>> _candidatesFor(BooruItem source) async {
    final List<String> queries = [
      for (final t in source.tagsList.where((t) => t.tagType != TagType.meta).take(4)) t.fullString.replaceAll('_', ' '),
      DoujinRecommendationEngine.baseTitle(
        (source.description ?? '').split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => ''),
      ),
    ].where((q) => q.trim().length > 2).toList();

    final List<BooruItem> out = [];
    final Set<String> seen = {source.postURL};
    for (final query in queries) {
      try {
        final response = await DioNetwork.get(
          '$_site/articles/search?keyword=${Uri.encodeQueryComponent(query)}&page=1',
          headers: getHeaders(),
        );
        for (final item in _itemsFromListing(response.data.toString())) {
          if (seen.add(item.postURL)) out.add(item);
        }
      } catch (_) {}
    }
    return out;
  }

  Future<void> _fillTags(List<BooruItem> items, {int limit = 8}) async {
    for (final item in items.take(limit)) {
      if (item.tagsList.length > 1) continue;
      try {
        final response = await DioNetwork.get(item.postURL, headers: getHeaders());
        item.tagsList = _tagsFrom(parse(response.data.toString()));
      } catch (_) {}
    }
  }

  Future<List<BooruItem>> _fetchRelated(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    return DoujinRecommendationEngine.related(source, await _candidatesFor(source));
  }

  Future<List<BooruItem>> _fetchRecommended(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    await _fillTags(candidates);
    String? artist;
    for (final tag in source.tagsList) {
      if (tag.tagType == TagType.artist) {
        artist = tag.fullString;
        break;
      }
    }
    return DoujinRecommendationEngine.rank(
      source,
      candidates,
      count: limit,
      sourceArtist: (artist?.isEmpty ?? true) ? null : artist,
    );
  }

  @override
  String? relatedVersionsQuery(BooruItem item) {
    final String id = item.serverId ?? '';
    return id.isEmpty ? null : 'related:$id';
  }
}
