import 'dart:async';
import 'dart:convert';

import 'package:fpdart/fpdart.dart';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';

import 'package:lolisnatcher/src/boorus/doujin/doujin_listing_tag_backfill.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_recommendation_engine.dart';
import 'package:lolisnatcher/src/boorus/doujin/doujin_tag_namespaces.dart';
import 'package:lolisnatcher/src/data/booru_item.dart';
import 'package:lolisnatcher/src/data/meta_tag.dart';
import 'package:lolisnatcher/src/data/response_error.dart';
import 'package:lolisnatcher/src/data/tag.dart';
import 'package:lolisnatcher/src/data/tag_suggestion.dart';
import 'package:lolisnatcher/src/data/tag_type.dart';
import 'package:lolisnatcher/src/handlers/booru_handler.dart';
import 'package:lolisnatcher/src/handlers/reader_handler.dart';
import 'package:lolisnatcher/src/handlers/schale_clearance_handler.dart';
import 'package:lolisnatcher/src/utils/dio_network.dart';
import 'package:lolisnatcher/src/utils/tools.dart';

/// niyaniya.moe — the Schale Network JSON API.
///
/// Clean and fully documented by observation:
///   `GET /books?s=<query>&page=N`   search / browse (`s`, not `search`)
///   `GET /books/popular?page=N`     the popular shelf
///   `GET /books/detail/{id}/{key}`  tags, page list, stats
///   `GET /books/favorites`          the signed-in account's favourites
///
/// Images live on two CDNs: `thumbnails.base` and a `fallback` host carrying
/// the identical path. Every URL this handler builds prefers the primary and
/// records the fallback, because the primary does intermittently fail.
///
/// The site publishes no related/recommended endpoints, so both sections are
/// generated by [DoujinRecommendationEngine] from titles and tags.
class SchaleHandler extends BooruHandler with DoujinListingTagBackfill, DoujinNamespacedTags {
  SchaleHandler(super.booru, super.limit);

  static const String _api = 'https://api.schale.network';
  static const String defaultSite = 'https://niyaniya.moe';

  /// The mirror actually configured, so Referer and Origin follow a switch to
  /// shupogaki.moe rather than staying pinned to niyaniya. The API is shared
  /// across mirrors; only the front end differs.
  String get _site {
    final String configured = booru.baseURL?.trim() ?? '';
    if (configured.isEmpty) return defaultSite;
    return configured.endsWith('/') ? configured.substring(0, configured.length - 1) : configured;
  }

  @override
  bool get hasReader => true;

  @override
  bool get hasLoadItemSupport => true;

  @override
  bool get shouldUpdateIteminTagView => true;

  @override
  bool get hasSizeData => true;

  // The API allows 5 requests a window. One at a time, paced, leaves room for
  // the requests the person actually made.
  @override
  int get tagBackfillConcurrency => 1;

  @override
  Duration get tagBackfillDelay => const Duration(milliseconds: 500);

  @override
  bool get hasTagSuggestions => true;

  @override
  bool get hasNativeOrSupport => false;

  @override
  String translateOrSyntax(String tags) => BooruHandler.dropOrGroupsWithWarning(tags, className);

  @override
  List<String> get animatedPreviewFilters => const [];

  /// The API rejects requests that don't look like they came from the site.
  ///
  /// The user agent matters beyond looking right. The clearance token is minted
  /// inside the challenge webview, which presents a plain Chrome UA because the
  /// site refuses to render a Turnstile for anything containing `wv`. Sending a
  /// DIFFERENT user agent when spending that token asks the API to honour a
  /// clearance earned by what looks like another client. Both halves now use
  /// the same string.
  @override
  Map<String, String> getHeaders() => {
    ...super.getHeaders(),
    'User-Agent': Tools.nonWebViewUserAgent,
    'Referer': '$_site/',
    'Origin': _site,
    'Accept': 'application/json',
    if (booru.apiKey?.isNotEmpty == true) 'Authorization': 'Bearer ${booru.apiKey}',
  };

  static dynamic _json(dynamic data) => data is String ? jsonDecode(data) : data;

  /// niyaniya keeps its images on erocdn mirrors, which serve them without a
  /// referer today. Sending the one a browser would send anyway costs nothing
  /// and means a future hotlink rule does not silently blank every cover.
  @override
  Map<String, String> getMediaHeaders() => {'Referer': '$_site/'};

  @override
  String validateTags(String tags) => tags.trim();

  @override
  String makePostURL(String id) => '$_site/g/$id';

  // ── the doujin query protocol ─────────────────────────────────────────
  // id:<n>         one exact gallery
  // related:<n>    other chapters / language versions of that work
  // recommend:<n>  generated recommendations
  // Everything else is an ordinary search.

  static final RegExp _protocol = RegExp(r'^(id|related|recommend):(.+)$', caseSensitive: false);

  static ({String kind, String id})? _parseProtocol(String tags) {
    final match = _protocol.firstMatch(tags.trim());
    if (match == null) return null;
    return (kind: match.group(1)!.toLowerCase(), id: match.group(2)!.trim());
  }

  @override
  String makeURL(String tags) {
    final protocol = _parseProtocol(tags);
    if (protocol != null) {
      // Handled in parseListFromResponse; this URL is just a cheap, valid
      // request so the base handler's fetch machinery stays happy.
      return '$_api/books?page=1';
    }
    // Chips display bare; schale matches on the namespaced form, so put the
    // namespace back before translating.
    final String query = translateQuery(qualifyQuery(tags));
    final int page = pageNum < 1 ? 1 : pageNum;
    if (query.isEmpty) return '$_api/books/popular?page=$page';
    // NB: the parameter is `s`. `q`, `search` and `tags` are all accepted and
    // silently ignored, which returns the whole unfiltered library.
    return '$_api/books?s=${Uri.encodeQueryComponent(query)}&page=$page';
  }

  /// Puts each bare tag back into its `namespace:name` form, leaving anything
  /// already qualified (and any operator prefix) alone.
  String qualifyQuery(String tags) {
    final List<String> out = [];
    for (final match in RegExp(r'"[^"]*"|\S+').allMatches(tags.trim())) {
      final String token = match.group(0)!;
      if (token.contains('"') || token.contains(':')) {
        out.add(token);
        continue;
      }
      final String prefix = token.startsWith('-') ? '-' : '';
      final String bare = prefix.isEmpty ? token : token.substring(1);
      out.add('$prefix${qualifyTag(bare)}');
    }
    return out.join(' ');
  }

  /// The app spells tags with underscores (`artist:asami_asami`); schale stores
  /// and matches them with spaces, and an underscored value simply finds
  /// nothing. Namespaces are left alone - they really are the bare words
  /// `artist`, `circle`, `parody`, `magazine`, `male`, `female`.
  @visibleForTesting
  static String translateQuery(String tags) {
    final String trimmed = tags.trim();
    if (trimmed.isEmpty) return '';

    final List<String> out = [];
    for (final match in RegExp(r'"[^"]*"|\S+').allMatches(trimmed)) {
      final String token = match.group(0)!;
      if (token.contains('"')) {
        out.add(token);
        continue;
      }
      String prefix = '';
      String rest = token;
      if (rest.startsWith('-')) {
        prefix = '-';
        rest = rest.substring(1);
      }
      if (rest.isEmpty) continue;

      final int colon = rest.indexOf(':');
      if (colon > 0) {
        out.add('$prefix${rest.substring(0, colon)}:${rest.substring(colon + 1).replaceAll('_', ' ')}');
      } else {
        out.add('$prefix${rest.replaceAll('_', ' ')}');
      }
    }
    return out.join(' ');
  }

  // ── parsing ───────────────────────────────────────────────────────────

  /// The listing's thumbnail object carries an absolute primary path plus a
  /// fallback on the second CDN.
  static (String primary, String fallback) _thumbUrls(dynamic thumbnail) {
    if (thumbnail is! Map) return ('', '');
    final String path = thumbnail['path']?.toString() ?? '';
    final String fallback = thumbnail['fallback']?.toString() ?? '';
    return (path, fallback.isEmpty ? path : fallback);
  }

  BooruItem? _itemFromEntry(dynamic row) {
    if (row is! Map) return null;
    final String id = row['id']?.toString() ?? '';
    final String key = row['key']?.toString() ?? '';
    if (id.isEmpty || key.isEmpty) return null;

    final (String thumb, String thumbFallback) = _thumbUrls(row['thumbnail']);
    final List<double>? dims = (row['thumbnail'] is Map && row['thumbnail']['dimensions'] is List)
        ? [for (final d in row['thumbnail']['dimensions'] as List) (d as num).toDouble()]
        : null;

    final item = BooruItem(
      fileURL: thumb,
      sampleURL: thumb,
      thumbnailURL: thumb,
      tagsList: const [],
      // The key is part of every detail lookup, so it rides along in the URL.
      postURL: '$_site/g/$id/$key',
      serverId: id,
      previewWidth: dims != null && dims.isNotEmpty ? dims[0] : null,
      previewHeight: dims != null && dims.length > 1 ? dims[1] : null,
    );
    item.description = row['title']?.toString() ?? '';
    final int pages = (row['pages'] as num?)?.toInt() ?? 0;
    if (pages > 0) item.fileCountHint.value = pages;
    // Second CDN for the same path, used when the primary 404s/times out.
    if (thumbFallback.isNotEmpty && thumbFallback != thumb) {
      item.sources = [thumbFallback];
    }
    _keys[id] = key;
    return item;
  }

  /// id -> key, so a gallery can be reopened from a stored favourite that
  /// only kept its id.
  static final Map<String, String> _keys = {};

  @override
  FutureOr<List> parseListFromResponse(dynamic response) async {
    final protocol = _parseProtocol(currentTags);
    if (protocol != null) {
      return switch (protocol.kind) {
        'id' => await _fetchOne(protocol.id),
        'related' => await _fetchRelated(protocol.id),
        _ => await _fetchRecommended(protocol.id),
      };
    }

    final data = _json(response.data);
    if (data is! Map) return [];
    return [
      for (final row in data['entries'] as List? ?? [])
        if (_itemFromEntry(row) != null) _itemFromEntry(row)!,
    ];
  }

  /// [parseListFromResponse] already builds finished items, so the base class's
  /// per-entry hook is a passthrough. Without this override it would replace
  /// every one of them with the default blank [BooruItem] and the grid would
  /// fill with empty cards.
  @override
  FutureOr<BooruItem?> parseItemFromResponse(dynamic responseItem, int index) =>
      responseItem is BooruItem ? responseItem : null;



  // ── tags ──────────────────────────────────────────────────────────────

  /// schale marks each tag with a numeric `namespace`. The codes below were
  /// each confirmed against the live API by searching a namespaced query and
  /// reading back which code the matching tag came home with:
  ///
  ///   1 artist · 2 circle · 3 parody · 4 magazine · 8 male · 9 female
  ///   10 mixed · 11 language · 12 other · 0 (or absent) plain tag
  ///
  /// Codes 5-7 were never observed and `character:`/`event:`/`publisher:`
  /// queries are rejected by the API, so anything unrecognised is left as a
  /// plain tag rather than guessed at - a wrong namespace would send the tag
  /// to the wrong section of the tag hub and break blacklist matching.
  static const Map<int, String> _namespaceCodes = {
    1: 'artist',
    2: 'circle',
    3: 'parody',
    4: 'magazine',
    8: 'male',
    9: 'female',
    10: 'mixed',
    11: 'language',
    12: 'other',
  };

  @visibleForTesting
  @visibleForTesting
  Tag? tagFromEntry(dynamic entry) {
    if (entry is! Map) return null;
    final String raw = entry['name']?.toString().trim() ?? '';
    if (raw.isEmpty) return null;
    final int code = (entry['namespace'] as num?)?.toInt() ?? 0;
    return namespacedTag(
      raw,
      _namespaceCodes[code],
      count: (entry['count'] as num?)?.toInt() ?? -1,
    );
  }

  @visibleForTesting
  List<Tag> tagsFromDetail(Map detail) {
    final List<Tag> tags = [];
    final Set<String> seen = {};
    for (final entry in detail['tags'] as List? ?? []) {
      final Tag? tag = tagFromEntry(entry);
      if (tag == null || !seen.add(tag.fullString)) continue;
      tags.add(tag);
    }
    return tags;
  }

  // ── detail ────────────────────────────────────────────────────────────

  /// The API publishes a request budget (`x-ratelimit-limit: 5`) and answers
  /// 429 once it is spent. Shared across every instance because the budget is
  /// per-client, not per-tab: a 429 in one tab means the next tab must wait too.
  static DateTime? _rateLimitedUntil;

  /// How long to stand down after a 429 when the response does not say.
  static const Duration rateLimitBackoff = Duration(seconds: 10);

  @visibleForTesting
  static void resetRateLimitForTests() => _rateLimitedUntil = null;

  @visibleForTesting
  static bool get isRateLimited =>
      _rateLimitedUntil != null && DateTime.now().isBefore(_rateLimitedUntil!);

  /// Reads `x-ratelimit-reset` (unix seconds) when the server sends one, so the
  /// wait is the server's number rather than a guess.
  @visibleForTesting
  static Duration backoffFrom(String? resetHeader, {DateTime? now}) {
    final DateTime at = now ?? DateTime.now();
    final int? epoch = int.tryParse(resetHeader ?? '');
    if (epoch != null) {
      final DateTime reset = DateTime.fromMillisecondsSinceEpoch(epoch * 1000, isUtc: true);
      final Duration wait = reset.difference(at.toUtc());
      // A reset far in the future is a header we have misread; do not sit out
      // the rest of the session over it.
      if (wait > Duration.zero && wait <= const Duration(minutes: 2)) return wait;
    }
    return rateLimitBackoff;
  }

  Future<void> _waitOutRateLimit() async {
    final DateTime? until = _rateLimitedUntil;
    if (until == null) return;
    final Duration left = until.difference(DateTime.now());
    if (left > Duration.zero) await Future.delayed(left);
    _rateLimitedUntil = null;
  }

  Future<Map?> _detail(String id, String key) async {
    for (int attempt = 0; attempt < 2; attempt++) {
      await _waitOutRateLimit();
      try {
        final response = await DioNetwork.get('$_api/books/detail/$id/$key', headers: getHeaders());
        if (response.statusCode != 200) return null;
        final data = _json(response.data);
        return data is Map ? data : null;
      } on DioException catch (e) {
        if (e.response?.statusCode != 429) return null;
        // Spent the budget. Stand down for everyone, then try once more.
        _rateLimitedUntil = DateTime.now().add(
          backoffFrom(e.response?.headers.value('x-ratelimit-reset')),
        );
        if (attempt == 1) return null;
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  /// The key for [id], from this session's listings or the item's own URL.
  String? _keyFor(String id, {String? postURL}) {
    final String? known = _keys[id];
    if (known != null && known.isNotEmpty) return known;
    if (postURL != null) {
      final parts = Uri.tryParse(postURL)?.pathSegments ?? const [];
      if (parts.length >= 3) return parts.last;
    }
    return null;
  }

  Future<List<BooruItem>> _fetchOne(String id) async {
    final String? key = _keyFor(id);
    if (key == null) return [];
    final detail = await _detail(id, key);
    if (detail == null) return [];
    final item = _itemFromDetail(id, key, detail);
    return item == null ? [] : [item];
  }

  BooruItem? _itemFromDetail(String id, String key, Map detail) {
    final thumbs = detail['thumbnails'];
    if (thumbs is! Map) return null;
    final String base = thumbs['base']?.toString() ?? '';
    final String fallbackBase = thumbs['fallback']?.toString() ?? base;
    final String mainPath = (thumbs['main'] is Map) ? (thumbs['main']['path']?.toString() ?? '') : '';

    final item = BooruItem(
      fileURL: '$base$mainPath',
      sampleURL: '$base$mainPath',
      thumbnailURL: '$base$mainPath',
      tagsList: [
        for (final t in detail['tags'] as List? ?? [])
          if (t is Map && (t['name']?.toString().isNotEmpty ?? false))
            Tag(t['name'].toString().replaceAll(' ', '_'), tagType: TagType.none),
      ],
      postURL: '$_site/g/$id/$key',
      serverId: id,
    );
    item.description = detail['title']?.toString() ?? '';
    final stat = detail['statistic'];
    if (stat is Map && stat['favorites'] != null) item.score = stat['favorites'].toString();
    if (fallbackBase.isNotEmpty && fallbackBase != base) {
      item.sources = ['$fallbackBase$mainPath'];
    }
    return item;
  }

  /// `/books` lists covers and titles only, so card tags come from the
  /// per-gallery detail call.
  @override
  Future<List<Tag>> tagsForListingItem(BooruItem item) async {
    final String id = item.serverId ?? '';
    final String? key = _keyFor(id, postURL: item.postURL);
    if (id.isEmpty || key == null) return const [];
    final detail = await _detail(id, key);
    if (detail == null) return const [];
    return tagsFromDetail(detail);
  }

  @override
  Future<({BooruItem? item, bool failed, String? error})> loadItem({
    required BooruItem item,
    dynamic cancelToken,
    bool withCapcthaCheck = false,
  }) async {
    final String id = item.serverId ?? '';
    final String? key = _keyFor(id, postURL: item.postURL);
    if (id.isEmpty || key == null) {
      return (item: null, failed: true, error: 'no gallery key');
    }

    final detail = await _detail(id, key);
    if (detail == null) return (item: null, failed: true, error: 'failed to load gallery');

    final thumbs = detail['thumbnails'];
    if (thumbs is! Map) return (item: null, failed: true, error: 'no page list');

    item.tagsList = tagsFromDetail(detail);
    if (item.description?.isEmpty ?? true) item.description = detail['title']?.toString() ?? '';

    // Readable pages are NOT in this response.
    //
    // `thumbnails.entries[]` is one 320px grid thumbnail per page, and the only
    // other size the thumbnail endpoint serves is 896 — which exists solely for
    // the cover (`thumbnails.main`). Substituting 896 into a non-cover entry's
    // path returns 404, and any other size returns 400. That is what the reader
    // was doing: showing 320px thumbnails as pages where they resolved at all.
    //
    // The real page list comes from POSTing to the same detail path with a
    // clearance token, which yields a `data` array; each entry then addresses
    // an image under /books/data/. Browsing needs none of this — only reading.
    final List? data = await _pageEntries(id, key);
    if (data == null) {
      return (
        item: null,
        failed: true,
        error: 'niyaniya needs a one-time check before it will serve pages. '
            'Open the reader again to complete it.',
      );
    }

    final String base = thumbs['base']?.toString() ?? '';
    final String fallbackBase = thumbs['fallback']?.toString() ?? base;
    final List entries = thumbs['entries'] as List? ?? const [];

    final List<BooruItem> pages = [];
    for (int index = 0; index < data.length; index++) {
      final entry = data[index];
      if (entry is! Map) continue;
      final String entryId = entry['id']?.toString() ?? '';
      final String entryKey = entry['key']?.toString() ?? '';
      if (entryId.isEmpty || entryKey.isEmpty) continue;

      final String url = readUrlFor(
        id: id,
        key: key,
        entryId: entryId,
        entryKey: entryKey,
        index: index,
        clearance: SchaleClearanceHandler.instance.token ?? '',
      );

      // The matching grid thumbnail, for the filmstrip and as a placeholder.
      // The API declares each page's dimensions, so the reader can reserve the
      // right space before the image arrives.
      final Map? thumb = index < entries.length && entries[index] is Map
          ? entries[index] as Map
          : null;
      final String thumbPath = thumb?['path']?.toString() ?? '';
      final List<double> dims = [
        for (final d in thumb?['dimensions'] as List? ?? const []) (d as num).toDouble(),
      ];

      final page = BooruItem(
        fileURL: url,
        sampleURL: url,
        thumbnailURL: thumbPath.isEmpty ? url : '$base$thumbPath',
        tagsList: const [],
        postURL: '$_site/g/$id/$key',
        fileWidth: dims.isNotEmpty ? dims[0] : null,
        fileHeight: dims.length > 1 ? dims[1] : null,
      );
      if (thumbPath.isNotEmpty && fallbackBase.isNotEmpty && fallbackBase != base) {
        page.sources = ['$fallbackBase$thumbPath'];
      }
      pages.add(page);
    }

    if (pages.isEmpty) return (item: null, failed: true, error: 'gallery has no pages');
    ReaderHandler.instance.registerBook(item, pages);
    item.fileCountHint.value = pages.length;
    return (item: item, failed: false, error: null);
  }

  /// The page list, which only exists once a clearance token is presented.
  ///
  /// Returns null when there is no usable clearance, so the caller can say so
  /// rather than showing an empty reader. A rejected token is dropped, so the
  /// next attempt asks for a fresh one instead of repeating a request that
  /// cannot succeed.
  Future<List?> _pageEntries(String id, String key) async {
    final SchaleClearanceHandler clearance = SchaleClearanceHandler.instance;

    for (int attempt = 0; attempt < 2; attempt++) {
      if (!clearance.hasToken) {
        final bool got = await clearance.requestClearance(_site);
        if (!got) return null;
      }

      try {
        final response = await DioNetwork.post(
          extraUrlFor(id: id, key: key, clearance: clearance.token ?? ''),
          headers: getHeaders(),
          options: Options(validateStatus: (_) => true),
        );
        if (response.statusCode == 200) {
          final data = _json(response.data);
          if (data is Map && data['data'] is List) return data['data'] as List;
          return null;
        }
        // 401/403 mean the token lapsed; anything else is not about clearance.
        if (response.statusCode == 401 || response.statusCode == 403) {
          clearance.invalidate();
          continue;
        }
        return null;
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  /// `POST /books/detail/{id}/{key}?crt=` — the page list.
  @visibleForTesting
  String extraUrlFor({required String id, required String key, required String clearance}) =>
      '$_api/books/detail/$id/$key?crt=${Uri.encodeQueryComponent(clearance)}';

  /// `GET /books/data/{id}/{key}/{entryId}/{entryKey}/{index}?crt=` — one page.
  @visibleForTesting
  String readUrlFor({
    required String id,
    required String key,
    required String entryId,
    required String entryKey,
    required int index,
    required String clearance,
  }) =>
      '$_api/books/data/$id/$key/$entryId/$entryKey/$index'
      '?crt=${Uri.encodeQueryComponent(clearance)}';


  // ── generated Related / Recommended ───────────────────────────────────

  /// Candidate pool: the source's own strongest tags, plus its title words,
  /// searched through the ordinary endpoint.
  Future<List<BooruItem>> _candidatesFor(BooruItem source, {int pages = 2}) async {
    final List<String> queries = [
      for (final t in source.tagsList.take(3)) t.fullString.replaceAll('_', ' '),
      DoujinRecommendationEngine.baseTitle(
        (source.description ?? '').split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => ''),
      ),
    ].where((q) => q.trim().length > 2).toList();

    final List<BooruItem> out = [];
    final Set<String> seen = {source.postURL};
    for (final query in queries.take(pages + 1)) {
      try {
        final response = await DioNetwork.get(
          '$_api/books?s=${Uri.encodeQueryComponent(query)}&page=1',
          headers: getHeaders(),
        );
        final data = _json(response.data);
        if (data is! Map) continue;
        for (final row in data['entries'] as List? ?? []) {
          final item = _itemFromEntry(row);
          if (item != null && seen.add(item.postURL)) out.add(item);
        }
      } catch (_) {
        // A dead candidate query just means fewer recommendations, never a
        // failed page.
      }
    }
    return out;
  }

  Future<BooruItem?> _sourceItem(String id) async {
    final String? key = _keyFor(id);
    if (key == null) return null;
    final detail = await _detail(id, key);
    if (detail == null) return null;
    return _itemFromDetail(id, key, detail);
  }

  Future<List<BooruItem>> _fetchRelated(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    return DoujinRecommendationEngine.related(source, candidates);
  }

  Future<List<BooruItem>> _fetchRecommended(String id) async {
    final source = await _sourceItem(id);
    if (source == null) return [];
    final candidates = await _candidatesFor(source);
    return DoujinRecommendationEngine.rank(source, candidates, count: limit);
  }

  @override
  String? relatedVersionsQuery(BooruItem item) {
    final String id = item.serverId ?? '';
    return id.isEmpty ? null : 'related:$id';
  }

  // ── tags ──────────────────────────────────────────────────────────────

  @override
  List<(String, String)> get tagNamespaceSections => const [
    ('artist', 'Artists'),
    ('circle', 'Circles'),
    ('parody', 'Series'),
    ('magazine', 'Magazines'),
    ('female', 'Female Tags'),
    ('male', 'Male Tags'),
    ('mixed', 'Mixed Tags'),
    ('tag', 'Tags'),
    ('other', 'Other'),
    ('language', 'Language'),
  ];


  @override
  List<MetaTag> availableMetaTags() => [
    StringMetaTag(name: 'Artist', keyName: 'artist'),
    StringMetaTag(name: 'Circle', keyName: 'circle'),
    StringMetaTag(name: 'Series', keyName: 'parody'),
    StringMetaTag(name: 'Magazine', keyName: 'magazine'),
    StringMetaTag(name: 'Female', keyName: 'female'),
    StringMetaTag(name: 'Male', keyName: 'male'),
    StringMetaTag(name: 'Language', keyName: 'language'),
  ];

  /// Suggestions come from the tag names attached to search results, which is
  /// the only tag surface the API exposes.
  @override
  Future<Either<ResponseError, List<TagSuggestion>>> getTagSuggestions(
    String input, {
    dynamic cancelToken,
  }) async {
    final String query = input.trim();
    if (query.isEmpty) return const Right([]);
    try {
      final response = await DioNetwork.get(
        '$_api/books?s=${Uri.encodeQueryComponent(query)}&page=1',
        headers: getHeaders(),
      );
      final data = _json(response.data);
      if (data is! Map) return const Right([]);
      final Set<String> names = {};
      for (final row in data['entries'] as List? ?? []) {
        if (row is Map && row['title'] != null) {
          for (final word in DoujinRecommendationEngine.titleTokens(row['title'].toString())) {
            if (word.startsWith(query.toLowerCase())) names.add(word);
          }
        }
      }
      return Right([
        for (final n in names.take(20)) TagSuggestion(tag: n, type: TagType.none),
      ]);
    } catch (e) {
      return Left(ResponseError(message: e.toString()));
    }
  }
}
